name: ATR Motors Infrastructure Deployment
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Choose Terraform Action
        options:
          - apply
          - destroy
        default: apply
        required: true

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.5.7

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Add a step to create the tfvars file before Terraform init
    - name: Create tfvars file
      run: |
        cat << EOF > terraform.tfvars
        aws_access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws_secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        EOF

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Conditional steps based on workflow dispatch input
    - name: Terraform Plan
      if: github.event.inputs.action == 'apply'
      run: terraform plan -no-color -out=tfplan

    - name: Terraform Apply
      if: github.event.inputs.action == 'apply' && github.ref == 'refs/heads/main'
      run: |
        terraform apply -auto-approve -var-file=terraform.tfvars

    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: |
        terraform destroy -auto-approve -var-file=terraform.tfvars

    # Optional: Display Load Balancer URL after apply
    - name: Display Load Balancer URL
      if: github.event.inputs.action == 'apply' && github.ref == 'refs/heads/main'
      run: |
        echo "Load Balancer URL: $(terraform output -raw load_balancer_dns)"
