name: ATR Motors Infrastructure Destroy

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.5.7

permissions:
  contents: read

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Create tfvars file
      run: |
        cat << EOF > terraform.tfvars
        aws_access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws_secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        EOF

    - name: Terraform Init
      run: terraform init

    # Add these debug steps
    - name: Terraform Show
      run: terraform show

    - name: Terraform State List
      run: terraform state list

    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve -var-file=terraform.tfvars -refresh=true

    # Force cleanup if needed
    - name: Force Cleanup
      if: failure()
      run: |
        terraform state list | xargs -I {} terraform state rm {}
        terraform destroy -auto-approve -var-file=terraform.tfvars
