name: ATR Motors Infrastructure Destroy

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.5.7

permissions:
  contents: read

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Create tfvars file
    - name: Create tfvars file
      run: |
        cat << EOF > terraform.tfvars
        aws_access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws_secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        EOF

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Destroy Infrastructure
    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve -var-file=terraform.tfvars
